### ISSUE TITLE
data format problems about training with custom dataset

### ISSUE THREAD

**Issue by chengdazhi** [carpedm20/BEGAN-tensorflow#16]
**When I directly train the model on cifar-10, I received:**

> tensorflow.python.framework.errors_impl.InvalidArgumentError: **CPU BiasOp only supports NHWC.**
	 [[Node: G/Conv/BiasAdd = BiasAdd[T=DT_FLOAT, data_format="NCHW", _device="/job:localhost/replica:0/task:0/cpu:0"](G/Conv/convolution, G/Conv/biases/read)]]

**Full stack trace:**

E tensorflow/core/common_runtime/executor.cc:594] Executor failed to create kernel. Invalid argument: CPU BiasOp only supports NHWC.
	 [[Node: G/Conv/BiasAdd = BiasAdd[T=DT_FLOAT, data_format="NCHW", _device="/job:localhost/replica:0/task:0/cpu:0"](G/Conv/convolution, G/Conv/biases/read)]]

Traceback (most recent call last):
  File "main.py", line 43, in <module>
    main(config)
  File "main.py", line 35, in main
    trainer.train()
  File "/media/bitss/0D53F42E56755822/BEGAN-tensorflow/trainer.py", line 140, in train
    result = self.sess.run(fetch_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: CPU BiasOp only supports NHWC.
	 [[Node: G/Conv/BiasAdd = BiasAdd[T=DT_FLOAT, data_format="NCHW", _device="/job:localhost/replica:0/task:0/cpu:0"](G/Conv/convolution, G/Conv/biases/read)]]

Caused by op u'G/Conv/BiasAdd', defined at:
  File "main.py", line 43, in <module>
    main(config)
  File "main.py", line 31, in main
    trainer = Trainer(config, data_loader)
  File "/media/bitss/0D53F42E56755822/BEGAN-tensorflow/trainer.py", line 92, in __init__
    self.build_model()
  File "/media/bitss/0D53F42E56755822/BEGAN-tensorflow/trainer.py", line 176, in build_model
    self.repeat_num, self.data_format, reuse=False)
  File "/media/bitss/0D53F42E56755822/BEGAN-tensorflow/models.py", line 11, in GeneratorCNN
    x = slim.conv2d(x, hidden_num, 3, 1, activation_fn=tf.nn.elu, data_format=data_format)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 907, in convolution
    outputs = layer.apply(inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 303, in apply
    return self.__call__(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 273, in __call__
    outputs = self.call(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/convolutional.py", line 169, in call
    data_format=utils.convert_data_format(self.data_format, 4))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1316, in bias_add
    return gen_nn_ops._bias_add(value, bias, data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 281, in _bias_add
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): CPU BiasOp only supports NHWC.
	 [[Node: G/Conv/BiasAdd = BiasAdd[T=DT_FLOAT, data_format="NCHW", _device="/job:localhost/replica:0/task:0/cpu:0"](G/Conv/convolution, G/Conv/biases/read)]]

**Comment by chengdazhi** [comment]
I can see the problem is caused by the slim.conv2d function in models.py. Note that if I convert the data format before calling conv2d, it works but at an extremely low speed.
