### ISSUE TITLE
can't train

### ISSUE THREAD

**Issue by jimmy4j** [carpedm20/BEGAN-tensorflow#25]
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1039, in _do_call
    return fn(*args)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1021, in _run_fn
    status, run_metadata)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_o
k_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_0_synthetic_inputs/random_shuffle_queue' is closed and has insufficient
 elements (requested 16, current size 0)
         [[Node: synthetic_inputs = QueueDequeueManyV2[component_types=[DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](sy
nthetic_inputs/random_shuffle_queue, synthetic_inputs/n)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 43, in <module>
    main(config)
  File "main.py", line 35, in main
    trainer.train()
  File "E:\Workspaces\ideaPro\pythondemo\began_tf\trainer.py", line 123, in train
    x_fixed = self.get_image_from_loader()
  File "E:\Workspaces\ideaPro\pythondemo\began_tf\trainer.py", line 349, in get_image_from_loader
    x = self.data_loader.eval(session=self.sess)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 569, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 3741, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 778, in run
    run_metadata_ptr)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: RandomShuffleQueue '_0_synthetic_inputs/random_shuffle_queue' is closed and has insufficient
 elements (requested 16, current size 0)
         [[Node: synthetic_inputs = QueueDequeueManyV2[component_types=[DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](sy
nthetic_inputs/random_shuffle_queue, synthetic_inputs/n)]]

Caused by op 'synthetic_inputs', defined at:
  File "main.py", line 43, in <module>
    main(config)
  File "main.py", line 30, in main
    config.data_format, config.split)
  File "E:\Workspaces\ideaPro\pythondemo\began_tf\data_loader.py", line 41, in get_loader
    min_after_dequeue=min_after_dequeue, name='synthetic_inputs')
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\input.py", line 1214, in shuffle_batch
    name=name)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\training\input.py", line 784, in _shuffle_batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\data_flow_ops.py", line 458, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\ops\gen_data_flow_ops.py", line 1328, in _queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\framework\ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): RandomShuffleQueue '_0_synthetic_inputs/random_shuffle_queue' is closed and has insufficient elements (req
uested 16, current size 0)
         [[Node: synthetic_inputs = QueueDequeueManyV2[component_types=[DT_UINT8], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](sy
nthetic_inputs/random_shuffle_queue, synthetic_inputs/n)]]

**Comment by shirishr** [comment]
I can confirm that I too get exactly same error as reported by jimmy4j
My environment consists of Windows10, CUDA8.0, Python 3.5, tensorflow 1.2, 
@jimmy4j Did you get past this error?
you all gurus out there...any ideas?

**Comment by afterblack** [comment]
I get same errors too, I find it may be caused by the data format. 
I have downloaded the  celebA data in advance. Refer to download.py, I created './data/CelebA/images' and putted the downloaded compressed file in './data'. 
Finally I commented out “if os.path.exists(data_path): print...balabala” and it worked.

**Comment by bison31205** [comment]
I get the same error too!
My environment consists of Windows7, Python 3.5, tensorflow 1.1.0 without GPU.
