### ISSUE TITLE
ValueError: Dimensions must be equal when using --use_authors_model

### ISSUE THREAD

**Issue by wohnjayne** [carpedm20/BEGAN-tensorflow#4]
With the `--use_authors_model` flag, I get a value error (probably related to the data format)

`(env) <me>@cuda4xl-02:~/Projects/BEGAN/src$ python main.py --use_gpu True --use_authors_model True`

The same command without the `--use_authors_model` flag works perfectly.

cheers and keep up the great work :+1: 

```
Traceback (most recent call last):
  File "main.py", line 42, in <module>
    main(config)
  File "main.py", line 30, in main
    trainer = Trainer(config, data_loader)
  File "/home/<me>/Projects/BEGAN/src/trainer.py", line 79, in __init__
    self.build_model()
  File "/home/<me>/Projects/BEGAN/src/trainer.py", line 164, in build_model
    G, self.G_var = G_enc(G_in, 0)
  File "/home/<me>/Projects/BEGAN/src/layers.py", line 97, in __call__
    vout = unboxn(convs[0](vout), 2)
  File "/home/<me>/Projects/BEGAN/src/layers.py", line 48, in __call__
    padding=self.padding, data_format=self.data_format), self.bias)
  File "/home/<me>/Projects/BEGAN/src/layers.py", line 78, in <lambda>
    def __init__(self, name, n, width, colors, depth, scales, nl=lambda x, y: x + y, data_format="NCHW"): 
  File "/home/<me>/Projects/BEGAN/env/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 821, in binary_op_wrapper
    return func(x, y, name=name)
  File "/home/<me>/Projects/BEGAN/env/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 73, in add
    result = _op_def_lib.apply_op("Add", x=x, y=y, name=name)
  File "/home/<me>/Projects/BEGAN/env/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/<me>/Projects/BEGAN/env/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2338, in create_op
    set_shapes_for_outputs(ret)
  File "/home/<me>/Projects/BEGAN/env/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1719, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/<me>/Projects/BEGAN/env/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1669, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/<me>/Projects/BEGAN/env/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/<me>/Projects/BEGAN/env/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 8 and 128 for 'add' (op: 'Add') with input shapes: [?,128,8,8], [128].

```

**Comment by carpedm20** [comment]
One of the author of the paper shared his code which is used in BEGAN so I once tried to add it. But I now think that model isn't that different and it may not affect the result that much (actually model descriped in the paper and one in the author's repo is quite different) so I quit to add it.

So I think it's better to remove that argument for now. Thanks for noticing this issue
